### PR TITLE
#11 testing 

### PR DESCRIPTION
**Pull request by Arditti93**
created test to run the price fucntion

### CODE REVIEW

**Comment by nmunro** [comment]
So the first line of the test file needs to be changed to `const order` instead of `const index` that's why these new tests aren't working, but absolutely wonderful you're writing tests!

**Comment by Arditti93** [comment]
Thank you!

**Review by DonnaK97 — COMMENTED** [review]
looks good to me.
Just a little tweaks; shall we "Order" instead of "order"? assume in index.js file, our order class is written with upper O.

**Review by DonnaK97 — APPROVED** [review]
looks good!

**Pull request closed without merging**
